/*!-----------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Version: 0.15.5(3d42593a5844407ab71d47b348ea3a8de5fec848)
 * Released under the MIT license
 * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
 *-----------------------------------------------------------*/

module.exports = {
    "vs/base/browser/ui/actionbar/actionbar": ["{0} ({1})"],
    "vs/base/browser/ui/aria/aria": [
		"{0} (ocorreu novamente)",
		"{0} (ocorreu {1} vezes)"
    ],
    "vs/base/browser/ui/findinput/findInput": ["Entrada"],
    "vs/base/browser/ui/findinput/findInputCheckboxes": [
		"Diferenciar Maiúsculas de Minúsculas",
		"Coincidir Palavra Inteira",
		"Usar Expressão Regular"
    ],
    "vs/base/browser/ui/findinput/replaceInput": [
		"Entrada",
		"Preservar caso"
    ],
    "vs/base/browser/ui/inputbox/inputBox": [
		"Erro: {0}",
		"Aviso: {0}",
		"Info: {0}"
    ],
    "vs/base/browser/ui/keybindingLabel/keybindingLabel": [
		"não vinculado"
    ],
    "vs/base/browser/ui/list/listWidget": [
		"{0}. Use as teclas de navegação para navegar."
    ],
    "vs/base/browser/ui/menu/menu": ["{0} ({1})"],
    "vs/base/browser/ui/tree/abstractTree": [
		"Limpar",
		"Desativar o filtro no tipo",
		"Habilitar o filtro no tipo",
		"Elementos não encontrados",
		"Combinados {0} de {1} elementos"
    ],
    "vs/base/common/keybindingLabels": [
		"Ctrl",
		"Shift",
		"Alt",
		"Windows",
		"Ctrl",
		"Shift",
		"Alt",
		"Super",
		"Control",
		"Shift",
		"Alt",
		"Comando",
		"Control",
		"Shift",
		"Alt",
		"Windows",
		"Control",
		"Shift",
		"Alt",
		"Super",
    ],
    "vs/base/common/severity": [
		"Erro",
		"Aviso",
		"Informação",
    ],
    "vs/base/parts/quickopen/browser/quickOpenModel": [
		"{0}, seletor",
		"seletor"
    ],
    "vs/base/parts/quickopen/browser/quickOpenWidget": [
		"Seletor rápido. Digite para filtrar resultados.",
		"Seletor rápido",
		"{0} Resultados"
    ],
    "vs/editor/browser/controller/coreCommands": [
        "&&Selecionar Tudo",
        "&&Desfazer",
        "&&Refazer",
    ],
    "vs/editor/browser/controller/textAreaHandler": [
        "O Editor não está acessível no momento. Pressione Alt+F1 para opções."
    ],
    "vs/editor/browser/widget/codeEditorWidget": [
        "O número de cursores foi limitado a {0}."
    ],
    "vs/editor/browser/widget/diffEditorWidget": [
        "Não é possível comparar os arquivos pois um deles é muito grande."
    ],
    "vs/editor/browser/widget/diffReview": [
        "Fechar",
        "nenhuma linha alterada",
        "1 linha alterada",
        "{0} linhas alteradas",
        "Diferença {0} de {1}: linha original {2}, {3}, linha modificada {4}, {5}",
        "branco",
        "{0} linha original {1} linha modificada {2}",
        "+ {0} linha modificada {1}",
        "- {0} linha original {1}",
        "Ir para a próxima diferença",
        "Ir para a diferença anterior"
    ],
    "vs/editor/browser/widget/inlineDiffMargin": [
        "Copiar linhas excluídas",
        "Copiar linha excluída",
        "Copiar linha excluída ({0})",
        "Reverter esta alteração",
        "Copiar linha excluída ({0})",
    ],
    "vs/editor/common/config/commonEditorConfig": [
        "Editor",
        "O número de espaços equivalentes a uma tabulação. Esta configuração é sobreposta com base no conteúdo do arquivo quando `#editor.detectIndentation#` está ligado.",
        "Insere espaços quanto pressionado Tab. Esta configuração é sobrescrita com base no conteúdo do arquivo quando '#editor.detectIndentation#' está habilitado.",
        "Quando um arquivo está sendo aberto, 'editor.tabSize' e 'editor.insertSpace' será detectado com base no conteúdo do arquivo.",
        "Remove o espaço em branco auto inserido à direita.",
        "Tratamento especial para arquivos grandes para desabilitar determinados recursos que fazem uso intensivo de memória.",
        "Controla se o auto-completar deve ser calculado baseado nas palavras no documento.",
        "Controla se o destaque semântico é mostrado para os idiomas que o suportam.",
        "Manter editores de visualização abertos mesmo quando pressionado duplo clique em seu conteúdo ou ao clicar em 'Escape'.",
        "Linhas acima este comprimento não serão indexadas por motivos de desempenho",
        "Tempo limite em milissegundos após o qual a computação diff é cancelada. Use 0 para nenhum tempo limite.",
        "Controla se o editor de diferenças mostra a comparação lado a lado ou na linha.",
        "Quando ativado, o editor diff ignora alterações no espaço em branco à esquerda ou à direita.",
        "Controla se o editor de diferenças mostra indicadores +/- para alterações adicionadas/removidas."
    ],
    "vs/editor/common/config/editorOptions": [
        "O editor irá utilizar a plataforma da API para detectar quando um leitor de tela está conectado.",
        "O editor será permanentemente otimizado para o uso de um leitor de tela.",
        "O editor nunca será otimizado para o uso de um leitor de tela.",
        "Controla quando o editor deve executar em modo otimizado para leitores de tela.",
        "Controla se um caractere de espaço é inserido ao comentar.",
        "Controla se a cópia sem nenhuma seleção copia a linha atual.",
        "Controla se a sequência de caracteres de Pesquisar no Widget encontrar é semeada de seleção do editor.",
        "Nunca ative Localizar na seleção automaticamente (padrão)",
        "Sempre ativar Localizar na seleção automaticamente",
        "Ativar Encontrar na seleção automaticamente quando várias linhas de conteúdo estão selecionadas.",
        "Controla se a busca será realizada no texto selecionado ou em todo o arquivo no editor.",
        "Controla se a Ferramenta Localizar deve ler ou modificar a área de transferência de busca compartilhada no macOS.",
        "Controla se o Widget de busca deve adicionar linhas extras no topo do editor. Se verdadeiro, você pode rolar além da primeira linha quando o Widget de busca está visível.",
        "Ativa/Desativa ligaduras de fonte.",
        "Configurações explícitas de recursos de fonte.",
        "Configura ligaduras de fonte ou recursos de fonte.",
        "Controla o tamanho da fonte em pixels.",
        "Mostrar exibição rápida dos resultados (padrão)",
        "Ir para o resultado principal e mostrar uma visão de espiada",
        "Ir para o resultado principal e habilite a navegação sem espiada para outras pessoas",
        "Essa configuração foi descontinuada. Por favor, use configurações separadas, como 'editor.editor.gotoLocation.multipleDefinitions' ou 'editor.editor.gotoLocation.multipleImplementations'.",
        "Controla o comportamento do comando 'Ir para definição' quando existem vários locais de destino.",
        "Controla o comportamento do comando 'Ir para definição de tipo' quando existem vários locais de destino.",
        "Controla o comportamento do comando 'Ir para declaração' quando existem vários locais de destino.",
        "Controla o comportamento do comando 'Ir para implementações' quando existem vários locais de destino.",
        "Controla o comportamento do comando 'Ir para referências' quando existem vários locais de destino.",
        "ID de comando alternativo que está sendo executado quando o resultado de 'Ir para definição' é o local atual.",
        "ID de comando alternativo que está sendo executado quando o resultado de 'Ir para Definição de Tipo' é o local atual.",
        "ID de comando alternativo que está sendo executado quando o resultado de 'Ir para declaração' é o local atual.",
        "ID de comando alternativo que está sendo executado quando o resultado de 'Ir para Implementação' é o local atual.",
        "ID de comando alternativo que está sendo executado quando o resultado de 'Ir para Referência' é o local atual.",
        "Controla se o foco é mostrado.",
        "Controla o atraso em milissegundos, após o qual sugestões rápidas serão exibidas.",
        "Controla se o foco deve permanecer visível quando o mouse é movido sobre ele.",
        "\nAtiva a lâmpada de ação de código no editor.",
        "Controla a altura da linha. Use 0 para computar a altura da linha a partir do tamanho da fonte.",
        "Controla se o minimapa é exibido.",
        "Controla o lado onde renderizar o minimapa.",
        "Controla quando o controle deslizante de minimapa é mostrado.",
        "Escala do conteúdo desenhado no minimapa: 1, 2 ou 3.",
        "Processa os caracteres reais em uma linha em vez de blocos de cor.",
        "Limite a largura do minimapa para desenhar no máximo um certo número de colunas.",
        "Permite que um pop-up que mostra informações de documentação e o tipo de parâmetro quando você digita.",
        "Controla se o menu de dicas do parâmetro é alternado ou fechado ao atingir o final da lista.",
        "Habilitar sugestões rápidas dentro de strings.",
        "Habilitar sugestões rápidas dentro de comentários.",
        "Habilitar sugestões rápidas fora de strings e comentários.",
        "Controla se as sugestões devem aparecer automaticamente ao digitar.",
        "Números de linhas não são renderizados.",
        "Números de linhas são renderizados em números absolutos.",
        "Números de linhas são renderizadas como distância em linhas até a posição do cursor.",
        "Números de linhas são renderizados a cada 10 linhas.",
        "Controla a exibição de números de linha.",
        "Renderiza réguas verticais após um certo número de caracteres de espaço. Use vários valores para várias réguas. Réguas não serão desenhadas se o array estiver vazio",
        "Inserir sugestão sem substituir o texto à direita do cursor.",
        "Inserir sugestão e substituir texto à direita do cursor.",
        "Controla se as palavras são sobrescritas ao aceitar conclusões. Observe que isso depende de extensões que optarem por esse recurso.",
        "Controla se as modificações inesperadas do texto ao aceitar conclusões devem ser destacadas, por exemplo, `insertMode` é` replace`, mas a conclusão suporta apenas `insert`.",
        "Controla se as sugestões de filtragem e ordenação valem para pequenos erros de digitação.",
        "Controla se ordena as palavras favoritas que aparecem perto do cursor.",
        "Controla se as seleções de sugestões lembradas são compartilhadas entre múltiplos espaços de trabalho e janelas (precisa de `#editor.suggestSelection#`).",
        "Controla se um trecho de código ativo impede sugestões rápidas.",
        "Controla se ícones em sugestões devem ser mostrados.",
        "Controla quantas sugestões o IntelliSense mostrará antes de mostrar uma barra de rolagem (no máximo 15).",
        "Essa configuração foi descontinuada. Em vez disso, use configurações separadas como 'editor.suggest.showKeywords' ou 'editor.suggest.showSnippets'.",
        "Quando habilitado, o IntelliSense mostra sugestões `method`.",
        "Quando habilitado, o IntelliSense mostra sugestões de `function`.",
        "Quando habilitado, o IntelliSense mostra sugestões `constructor`.",
        "Quando habilitado, o IntelliSense mostra sugestões `field`.",
        "Quando habilitado, o IntelliSense mostra sugestões `variable`.",
        "Quando habilitado, o IntelliSense mostra sugestões `class`.",
        "Quando habilitado, o IntelliSense mostra sugestões `struct`.",
        "Quando habilitado, o IntelliSense mostra sugestões `interface`.",
        "Quando habilitado, o IntelliSense mostra sugestões `module`.",
        "Quando habilitado, o IntelliSense mostra sugestões `property`.",
        "Quando habilitado, o IntelliSense mostra sugestões `event`.",
        "Quando habilitado, o IntelliSense mostra sugestões `operator`.",
        "Quando habilitado, o IntelliSense mostra sugestões `unit`.",
        "Quando habilitado, o IntelliSense mostra sugestões `value`.",
        "Quando habilitado, o IntelliSense mostra sugestões `constant`.",
        "Quando habilitado, o IntelliSense mostra sugestões `enum`.",
        "Quando habilitado, o IntelliSense mostra sugestões `enumMember`.",
        "Quando habilitado, o IntelliSense mostra sugestões `keyword`.",
        "Quando habilitado, o IntelliSense mostra sugestões `text`.",
        "Quando habilitado, o IntelliSense mostra sugestões `color`.",
        "Quando habilitado, o IntelliSense mostra sugestões `file`.",
        "Quando habilitado, o IntelliSense mostra sugestões `reference`.",
        "Quando habilitado, o IntelliSense mostra sugestões `customcolor`.",
        "Quando habilitado, o IntelliSense mostra sugestões `folder`.",
        "Quando habilitado, o IntelliSense mostra sugestões `typeParameter`.",
        "Quando habilitado, o IntelliSense mostra sugestões `snippet`.",
        "Controla a visibilidade da barra de status na parte inferior do widget de sugestão.",
        "Controla se as sugestões devem ser aceitas em caracteres de confirmação. Por exemplo, em JavaScript, o ponto e vírgula (';') pode ser um caractere de confirmação que aceita uma sugestão e digita esse caractere.",
        "Aceita uma sugestão ao pressionar 'Enter' apenas quando uma alteração textual é feita.",
        "Controla se as sugestões devem ser aceitas ao pressionar 'Enter', além de 'Tab'. Ajuda a evitar a ambiguidade entre a inserção de novas linhas ou ao aceitar sugestões.",
        "Controla o número de linhas no editor que podem ser lidas por um leitor de tela. Aviso: isso tem uma implicação de desempenho para números maiores do que o padrão.",
        "Conteúdo do editor",
        "Use as configurações de idioma para determinar quando fechar os parênteses automaticamente.",
        "Fechar os parênteses automaticamente somente quando o cursor está à esquerda do espaço em branco.",
        "Controla se o editor deve fechar automaticamente os colchetes depois do usuário abrir um colchete.",
        "Digite o fechamento de aspas ou colchetes somente se eles foram inseridos automaticamente.",
        "Controla se o editor deve digitar sobre aspas ou colchetes de fechamento.",
        "Use as configurações de idioma para determinar quando fechar as aspas automaticamente.",
        "Fechar aspas automaticamente somente quando o cursor está à esquerda do espaço em branco.",
        "Controla se o editor deve fechar automaticamente aspas depois que o usuário adiciona aspas de abertura.",
        "O editor não inserirá o recuo automaticamente.",
        "O editor manterá o recuo da linha atual.",
        "O editor manterá a indentação da linha atual e honrará os colchetes definidos pela linguagem.",
        "O editor manterá o recuo da linha atual, honrará os colchetes definidos pelo idioma e invocará as onEnterRules especiais definidas pelos idiomas.",
        "O editor manterá o recuo da linha atual, honrará os colchetes definidos pelo idioma, invocará onEnterRules especiais definidas pelos idiomas e honrará indentationRules definidas pelos idiomas.",
        "Controla se o editor deve ajustar automaticamente o recuo quando os usuários digitam, colam, movem ou recuam linhas.",
        "Use as configurações de idioma para determinar quando envolver automaticamente as seleções.",
        "Envolver com aspas, mas não os colchetes.",
        "Envolver com colchetes, mas não com aspas.",
        "Controla se o editor deve envolver automaticamente as seleções.",
        "Controla se o editor mostra CodeLens.",
        "Controla se o editor deve processar os decoradores de cor inline e o seletor de cores.",
        "Controla se o realce de sintaxe deve ser copiado para a área de transferência.",
        "Controla o estilo de animação do cursor.",
        "Controla-se a animação de cursor suave deve ser ativada.",
        "Controla o estilo do cursor.",
        "Controla o número mínimo de linhas visíveis antes e depois do cursor. Conhecido como 'scrollOff' ou 'scrollOffset' em alguns outros editores.",
        "`cursorSurroundingLines` é aplicado somente quando acionado pelo teclado ou pela API.",
        "'cursorSurroundingLines' é aplicada sempre.",
        "Controla quando `cursorSurroundingLines` deve ser imposto.",
        "Controla a largura do cursor quando '#editor.cursorStyle#' é definido como 'linha'.",
        "\nControla se o editor deve permitir a movimentação de seleções por meio de arrastar e soltar.",
        "Multiplicador de velocidade de rolagem ao pressionar 'Alt'.",
        "Controla se o editor tem o dobramento de código habilitado.",
        "Usar uma estratégia de dobramento específica à linguagem se estiver disponível, senão a baseada em indentação.",
        "Controla se o editor deve destacar intervalos dobrados.",
        "Controla a família de fontes.",
        "Controla a espessura da fonte.",
        "Controla se o editor deve formatar automaticamente o conteúdo colado. Um formatador deve estar disponível e o formatador deve ser capaz de Formatar um intervalo em um documento.",
        "Controla se o editor deve formatar automaticamente a linha depois de digitar.",
        "Controla se o editor deve renderizar a margem vertical de ícones. A margem vertical de ícones é usada primordialmente na depuração",
        "Controla se o cursor deve ser oculto na régua de visão geral.",
        "Controla se o editor deve destacar o guia ativo de recuo.",
        "Controla o espaçamento de letras, em pixels",
        "Controla se o editor deve detectar links e torná-los clicáveis.",
        "Destacar colchetes correspondentes.",
        "Um multiplicador a ser usado no 'deltaX' e 'deltaY' nos eventos de rolagem da roda do mouse.",
        "Ampliar a fonte do editor ao usar a roda do mouse e pressionando a tecla 'Ctrl'.",
        "Mesclar vários cursores quando eles estão sobrepostos.",
        "Mapeia para 'Control' no Windows e Linux e para 'Command' no macOS.",
        "Mapeia para 'Alt' no Windows e Linux e 'Option' no macOS.",
        "O modificador a ser usado para adicionar vários cursores com o mouse. Os gestos do mouse de Ir Para Definição e Abrir Link irão adaptar-se de forma que eles não entrem em conflito com o modificador multicursor. [Leia mais] (https://code.visualstudio.com/docs/editor/codebasics#_multicursor-modifier).",
        "Cada cursor cola uma única linha do texto.",
        "Cada cursor cola o texto completo.",
        "Controla a colagem quando a contagem de linhas do texto colado coincide com a contagem de cursor.",
        "Controla se o editor deve destacar as ocorrências de símbolos semânticos.",
        "Controla se a borda deve ser desenhada em torno da régua de visão geral.",
        "Focar na árvore ao abrir o Espiar",
        "Focar o editor ao abrir a espiada",
        "Controla se o editor embutido deve ser focado ou a árvore no widget de visualização.",
        "Controla o atraso em milissegundos, após o qual sugestões rápidas serão exibidas.",
        "Controla se o editor deve processar caracteres de controle.",
        "Controla se o editor deve processar guias de recuos.",
        "Renderiza o último número da linha quando o arquivo termina com uma nova linha.",
        "Destacar tanto a calha quanto a linha atual.",
        "Controla como o editor deve desenhar o destaque de linha atual.",
        "Renderize caracteres de espaço em branco exceto por espaços únicos em branco entre as palavras.",
        "Renderize caracteres de espaço em branco somente no texto selecionado.",
        "Controla como o editor deve processar caracteres de espaço em branco.",
        "Controla se a seleção deve ter cantos arredondados.",
        "Controla o número de caracteres extras, além do qual o editor irá rolar horizontalmente.",
        "Controla se o editor irá rolar além da última linha.",
        "Controla se a área de transferência primária Linux deve ser suportada.",
        "Controla se o editor deve destacar correspondências semelhantes à seleção.",
        "Mostrar os controles dobráveis somente quando o mouse está sobre a calha.",
        "Controla o esmaecimento de código não utilizado.",
        "Mostre sugestões de trecho acima de outras sugestões.",
        "Mostre sugestões de trecho abaixo de outras sugestões.",
        "Mostre sugestões de trechos com outras sugestões.",
        "Não mostre sugestões de trecho.",
        "Controla se os snippets são exibidos juntamente com as outras sugestões e como eles são ordenados.",
        "Controla se o editor irá rolar usando uma animação.",
        "Tamanho da fonte para a ferramenta sugerida. Quando definido como '0', o valor de '#editor.fontSize#' será usado.",
        "Altura da linha para a ferramenta sugerida. Quando definido como '0', o valor de '#editor.lineHeight#' será usado.",
        "Controla se as sugestões devem aparecer automaticamente ao digitar caracteres de gatilho.",
        "Escolha sempre a primeira sugestão.",
        "Selecione sugestões recentes, a não ser mais digitando seleciona um, por exemplo, ' console. | -> console. log ' porque 'log' foi concluída recentemente.",
        "Selecione sugestões baseadas em prefixos anteriores que completaram as sugestões, por exemplo, 'co -> console' e 'con -> const'.",
        "Controla como as sugestões são pré-selecionados quando estiver mostrando a lista de sugestões.",
        "A guia completa irá inserir a melhor sugestão de correspondência quando pressionado tab.",
        "Desative as conclusões de guias.",
        "Trechos de guias completos quando há prefixos correspondes. Funciona melhor quando 'quickSuggestions' não estão habilitadas.",
        "Habilita conclusões de guias.",
        "Inserção e exclusão de espaço em branco segue paradas de tabulação.",
        "Caracteres que serão usados como separadores de palavras ao fazer navegação relacionada a palavras ou operações",
        "As linhas nunca serão quebradas.",
        "As linhas serão quebradas na largura de visualização",
        "As linhas serão quebradas conforme a configuração `#editor.wordWrapColumn#`.",
        "As linhas serão quebradas no mínimo entre a largura de visualização e `#editor.wordWrapColumn#`.",
        "Controla como as linhas devem ser dispostas.",
        "Controla a quebra de coluna do editor quando `#editor.wordWrap#` é `wordWrapColumn` ou `bounded`",
        "Sem recuo. Quebras de linhas começam na coluna 1.",
        "Quebras de linhas tem o mesmo recuo que o pai.",
        "Quebras de linhas tem recuo +1 em direção ao pai.",
        "Quebras de linhas tem recuo +2 em direção ao pai.",
        "Controla o recuo das quebras de linhas.",
        "Assume que todos os caracteres tenham a mesma largura. Este é um algoritmo rápido que funciona corretamente para fontes monoespaçadas e certos scripts (como caracteres latinos) em que os glifos têm largura igual.",
        "Delega a computação dos pontos de quebra ao navegador. Este é um algoritmo lento, que pode causar congelamentos para arquivos grandes, mas funciona corretamente em todos os casos.",
        "Controla o algoritmo que calcula os pontos de quebra."
    ],
    "vs/editor/common/modes/modesRegistry": [
        "Texto Sem Formatação"
    ],
    "vs/editor/common/standaloneStrings": [
        "Nenhuma seleção",
        "Linha {0}, Coluna {1} ({2} selecionado)",
        "Linha {0}, Coluna {1}",
        "{0} seleções ({1} caracteres selecionados)",
        "{0} seleções",
        "Agora alterando a configuração 'accessibilitySupport' para 'on'.",
        "Abrindo a página de documentação de Acessibilidade do editor.",
        "em um painel somente leitura de um editor de comparação.",
        "em um painel de um editor de comparação.",
        " em um editor de código somente leitura",
        " em um editor de código",
        "Para configurar o editor para ser otimizado para uso com um Leitor de Tela pressione Command+E agora.",
        "Para configurar o editor para ser otimizado para uso com um Leitor de Tela pressione Control+E agora.",
        "O editor é configurado para ser otimizado para uso com um Leitor de Tela.",
        "O editor é configurado para não ser otimizado para uso com um Leitor de Tela, que não é o caso neste momento.",
        "Pressionando Tab no editor corrente irá mover o foco para o próximo elemento focável. Mude este comportamento ao pressionar {0}.",
        "Pressionando Tab no editor corrente irá mover o foco para o próximo elemento focável. O comando {0} não pode ser ativado atualmente por uma tecla.",
        "Pressionando Tab no editor atual irá inserir um caractere Tab. Mude este comportamente ao pressionar {0}.",
        "Pressionando Tab no editor atual irá inserir um caractere Tab. O comando {0} não pode ser ativado atualmente por uma tecla.",
        "Pressione Command + H agora para abrir uma janela do navegador com mais informações relacionadas à acessibilidade do editor.",
        "Pressione Ctrl + H para abrir uma janela do navegador com mais informações relacionadas à acessibilidade do editor.",
        "Você pode ignorar esta dica de ferramenta e retornar ao editor pressionando Escape ou Shift+Escape.",
        "Mostrar ajuda de acessibilidade",
        "Desenvolvedor: Inspecionar Tokens",
        "Ir para Linha {0} e caractere {1}",
        "Ir para Linha {0}",
        "Digite uma linha entre 1 e {0} para navegar até ela.",
        "Digite um caractere entre 1 e {0} para navegar até ele.",
        "Linha Atual: {0}. Ir para Linha: {1}",
        "Digite o número de uma linha, seguido opcionalmente por dois pontos, e o número de um caractere para nagevar até.",
        "Ir para Linha...",
        "comandos {0}, {1}",
        "comandos {0}",
        "Digite o nome da ação que deseja executar",
        "Paleta de comando",
        "símbolos {0}",
        "Digite o nome do identificador que deseja navegar até",
        "Ir para o símbolo...",
        "símbolos ({0})",
        "módulos ({0})",
        "classes ({0})",
        "interfaces ({0})",
        "métodos ({0})",
        "funções ({0})",
        "propriedades ({0})",
        "variáveis ({0})",
        "variáveis ({0})",
        "construtores ({0})",
        "chamadas ({0})",  
        "Conteúdo do editor",
        "Pressione Ctrl+F1 para opções de acessibilidade.",
        "Pressione Alt+F1 para opções de acessibilidade.",
        "Alternar tema de alto contraste",
        "{0} edições feitas em {1} arquivos"
    ],
    "vs/editor/common/view/editorColorRegistry": [
        "Cor de fundo para a posição do cursor  na seleção de linhas.",
        "Cor de fundo para a borda em volta da linha na posição do cursor",
        "Cor de tela de fundo de intervalos destacados, por exemplo, pelos recursos de abertura e localização rápidas. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor de fundo para a borda em volta do intervalo destacado.",
        "Cor de fundo do símbolo destacado, como para ir para a definição ou para o símbolo seguinte/anterior. A cor não deve ser opaca para não ocultar as decorações subjacentes.",
        "Cor de fundo da borda em torno de símbolos destacados.",
        "Cor do cursor no editor.",
        "A cor de fundo do cursor do editor. Permite customizar a cor de um caractere sobreposto pelo bloco do cursor.",
        "Cor dos caracteres em branco no editor",
        "Cor das guias de indentação do editor.",
        "Cor das guias de indentação do editor ativo.",
        "Cor dos números de linha do editor.",
        "Cor dos números de linhas do editor",
        "A Identificação foi descontinuada. Use 'editorLineNumber.activeForeground'.",
        "Cor das réguas do editor.",
        "Cor do primeiro plano das lentes de código do editor",
        "Cor de fundo atrás do colchetes correspondentes",
        "Cor para as caixas de colchetes correspondentes",
        "Cor da borda da régua de visão geral.",
        "Cor de fundo da separação do editor.O separador contém os glifos das margens e os números de linha.",
        "Cor da borda do código-fonte desnecessário (não usado) no editor.",
        "Opacidade do código-fonte desnecessário (não usado) no editor. Por exemplo, \"#000000c0\" processará o código com 75% de opacidade. Para temas de alto contraste, use a cor do tema 'editorUnnecessaryCode.border' para sublinhar o código desnecessário em vez de desvanecê-lo.",
        "Cor do marcador de régua da visão geral para destaques de intervalo. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Visão geral da cor do marcador da régua para erros.",
        "Visão geral da cor do marcador da régua para avisos.",
        "Visão geral da cor do marcador da régua para informações."
    ],
    "vs/editor/contrib/bracketMatching/bracketMatching": [
        "Visão geral da cor do marcador da régua para colchetes correspondentes.",
        "Ir para Colchete",
        "Selecionar para Colchetes.",
        "Ir para &&Colchete"
    ],
    "vs/editor/contrib/caretOperations/caretOperations": [
        "Mover texto selecionado para a esquerda",
        "Mover o texto selecionado para a direita"
    ],
    "vs/editor/contrib/caretOperations/transpose": [
        "Transpor  letras"
    ],
    "vs/editor/contrib/clipboard/clipboard": [
        "Recortar",
        "Recorta&&r",
        "Copiar",
        "&&Copiar",
        "Colar",
        "&&Colar",
        "Copiar com realce de sintaxe"
    ],
    "vs/editor/contrib/codeAction/codeActionCommands": [
        "Tipo de ação de código para executar.",
        "Controles quando as ações retornadas são aplicadas.",
        "Aplique sempre a primeira ação de código retornada.",
        "Aplique a primeira ação de código retornada se for a única.",
        "Não aplique as ações de código retornadas.",
        "Controla se apenas as ações de código preferenciais devem ser retornadas.",
        "Ocorreu um erro desconhecido ao aplicar a ação do código",
        "Correção Rápida...",
        "Nenhuma ação disponível",
        "Nenhuma ação de código preferencial disponível para '{0}'",
        "Não há ações de código disponíveis para '{0}'",
        "Não há ações de código preferenciais disponíveis",
        "Nenhuma ação disponível",
        "Refatorar...",
        "Não há refatorações preferenciais disponíveis para '{0}'",
        "Nenhuma refatoração disponível para '{0}'",
        "Não há refatorações preferenciais disponíveis",
        "Nenhuma refatoração disponível",
        "Ação de Origem...",
        "Não há ações de origem preferenciais disponíveis para '{0}'",
        "Não há ações de origem disponíveis para '{0}'",
        "Não há ações de origem preferenciais disponíveis",
        "Não há ações de origem disponíveis",
        "Organizar Imports",
        "Nenhuma ação de organização de imports disponível",
        "Corrigir tudo",
        "Nenhuma ação de correção geral disponíveis",
        "Auto correção...",
        "Sem auto correções disponíveis"
    ],
    "vs/editor/contrib/codeAction/lightBulbWidget": [
        "Mostrar correções. Correção preferencial disponível ({0})",
        "Mostrar correções ({0})",
        "Mostrar correções"
    ],
    "vs/editor/contrib/comment/comment": [
        "Alternar Comentário de Linha",
        "&&Alternar Linha de Comentário",
        "Adicionar Comentário de Linha",
        "Remover Comentário de Linha",
        "Alternar Comentário de Bloco",
        "Alternar &&Bloco de Comentário"
    ],
    "vs/editor/contrib/contextmenu/contextmenu": [
        "Mostrar o menu de contexto do editor"
    ],
    "vs/editor/contrib/cursorUndo/cursorUndo": [
        "Desfazer Cursor",
        "Cursor Refazer"
    ],
    "vs/editor/contrib/documentSymbols/outlineTree": [
        "A cor de primeiro plano para símbolos de matriz. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor de primeiro plano para símbolos booleanos. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos da classe. Estes símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos de cor. Estes símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos constantes. Esses símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos do construtor. Estes símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos do enumerador. Esses símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor de primeiro plano para símbolos de membros do enumerador. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor de primeiro plano para símbolos de eventos. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor de primeiro plano para símbolos de campo. Esses símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor de primeiro plano para símbolos de arquivo. Esses símbolos aparecem no contorno, na trilha e no widget de sugestão.",
        "A cor do primeiro plano para símbolos da pasta. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos da função. Estes símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor de primeiro plano para símbolos de interface. Esses símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos chaves. Estes símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos da palavra-chave. Estes símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos do método. Esses símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos do módulo. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos do namespace. Estes símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos nulos. Esses símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos numéricos. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos de objeto. Estes símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos do operador. Esses símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor do primeiro plano para símbolos de pacote. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos da propriedade. Estes símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos de referência. Estes símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor de primeiro plano para símbolos de trecho. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos de string. Esses símbolos aparecem no contorno, na trilha de navegação, e no widget de sugestão.",
        "A cor de primeiro plano para símbolos de estrutura. Estes símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos de texto. Estes símbolos aparecem no contorno, na trilha de navegação, e sugerem widget.",
        "A cor de primeiro plano para símbolos de parâmetro de tipo. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos de unidade. Esses símbolos aparecem no contorno, na trilha de navegação e no widget de sugestão.",
        "A cor do primeiro plano para símbolos variáveis. Estes símbolos aparecem no contorno, na trilha de navegação, e sugerem widget."
    ],
    "vs/editor/contrib/find/findController": [
        "Encontrar",
        "&&Localizar",
        "Procurar Com a Seleção",
        "Localizar Próximo",
        "Localizar Próximo",
        "Localizar Anterior",
        "Localizar Anterior",
        "Localizar Próxima Seleção",
        "Localizar Seleção Anterior",
        "Substituir",
        "&&Substituir"
    ],
    "vs/editor/contrib/find/findWidget": [
        "Encontrar",
        "Encontrar",
        "Correspondência anterior",
        "Próxima correspondência",
        "Localizar na seleção",
        "Fechar",
        "Substituir",
        "Substituir",
        "Substituir",
        "Substituir Tudo",
        "Alternar modo de Substituição",
        "Apenas os primeiros {0} resultados serão destacados, mas todas as operações de busca funcionam em todo o texto.",
        "{0} de {1}",
        "Nenhum resultado",
        "{0} encontrado",
        "{0} encontrada para '{1}'",
        "{0} encontrada para '{1}', em {2}",
        "{0} encontradas para '{1}'",
        "Ctrl + Enter agora insere quebra de linha em vez de substituir tudo. Você pode modificar o configuração de Teclas para editor.action.replaceAll para substituir esse comportamento."
    ],
    "vs/editor/contrib/folding/folding": [
        "Abrir",
        "Abrir recursivamente",
        "Colapsar",
        "Alternar dobra",
        "Colapsar recursivamente",
        "Fechar Todos os Comentários de Bloco",
        "Fechar Todas as Regiões",
        "Abrir Todas as Regiões",
        "Colapsar tudo",
        "Abrir tudo",
        "Nível de colapsamento {0}",
        "Cor de fundo atrás de faixas dobradas. A cor não deve ser opaca para não esconder decorações subjacentes."
    ],
    "vs/editor/contrib/fontZoom/fontZoom": [
        "Editor de Fonte 'mais Zoom'",
        "Editor de fonte ' menos Zoom '",
        "Editor de Fonte 'redefinir Zoom'"
    ],
    "vs/editor/contrib/format/format": [
        "1 edição de formatação feita na linha {0}",
        "{0} edições de formatação feitas na linha {1}",
        "Feita 1 edição de formatação entre as linhas {0} e {1}",
        "Feitas {0} edições de formatação entre as linhas {1} e {2}"
    ],
    "vs/editor/contrib/format/formatActions": [
        "Formatar Documento",
        "Formatar Seleção"
    ],
    "vs/editor/contrib/gotoError/gotoError": [
        "Ir para o Próximo Problema (Erro, Aviso, Informação)",
        "Ir para o Problema Anterior (Erro, Aviso, Informação)",
        "Ir para Próximo Problema nos Aquivos (Erro, Aviso, Informação)",
        "Ir para o problema anterior em arquivos (Erro, aviso, Informação)",
        "Próximo &&Problema",
        "Problema &&Anterior"
    ],
    "vs/editor/contrib/gotoError/gotoErrorWidget": [
        "{0} de {1} problemas",
        "{0} de {1} problema",
        "Cor de marcação de erro da ferramenta de edição.",
        "Cor de marcação de aviso da ferramenta de edição.",
        "Cor de marcação de informação da ferramenta de edição.",
        "Cor de marcação de fundo da ferramenta de edição.",
    ],
    "vs/editor/contrib/gotoSymbol/goToCommands": [
        "Inspecionar",
        "Definições",
        "Não foi encontrada definição para '{0}'",
        "Nenhuma definição encontrada",
        "Ir para Definição",
        "Ir para &&Definição",
        "Abrir definição ao lado",
        "Inspecionar definição",
        "Declarações",
        "Nenhuma declaração encontrada para '{0}'",
        "Nenhuma declaração encontrada",
        "Ir para Declaração",
        "Ir para &&Declaração",
        "Nenhuma declaração encontrada para '{0}'",
        "Nenhuma declaração encontrada",
        "Inspecionar declaração",
        "Definições de tipo",
        "Nenhuma definição de tipo encontrada para '{0}'",
        "Nenhuma definição de tipo encontrada",
        "Ir para a definição de tipo",
        "Ir para &&definição de tipo",
        "Inspecionar definição de tipo",
        "Implementações",
        "Nenhuma implementação encontrada para '{0}'",
        "Nenhuma implementação encontrada",
        "Ir para implementações",
        "Ir para &&Implementações",
        "Inspecionar implementações",
        "Não foram encontradas referências para '{0}'",
        "Não foram encontradas referências",
        "Ir para Referências",
        "Ir para e &&Referências",
        "Referências",
        "Inspecionar Referências",
        "Referências",
        "Ir para qualquer símbolo",
        "Localizações",
        "Nenhum resultado para '{0}'",
        "Referências",
    ],
    "vs/editor/contrib/gotoSymbol/link/goToDefinitionAtPosition": [
        "Clique para mostrar {0} definições."
    ],
    "vs/editor/contrib/gotoSymbol/peek/referencesController": [
        "Carregando...",
        "{0} ({1})"
    ],
    "vs/editor/contrib/gotoSymbol/peek/referencesTree": [
        "Falha ao resolver arquivo.",
        "{0} referências",
        "{0} referência"
    ],
    "vs/editor/contrib/gotoSymbol/peek/referencesWidget": [
        "nenhuma visualização disponível",
        "Referências",
        "Nenhum resultado",
        "Referências"
    ],
    "vs/editor/contrib/gotoSymbol/referencesModel": [
        "símbolo em {0} na linha {1} e coluna {2}",
        "1 símbolo em {0}, caminho completo {1}",
        "{0} símbolos em {1}, caminho completo {2}",
        "Nenhum resultado encontrado",
        "Encontrado 1 símbolo em {0}",
        "Encontrados {0} símbolos em {1}",
        "Encontrados {0} símbolos em {1} arquivos"
    ],
    "vs/editor/contrib/gotoSymbol/symbolNavigation": [
        "Símbolo {0} de {1}, {2} para a próxima",
        "Símbolo {0} de {1}"
    ],
    "vs/editor/contrib/hover/hover": [
        "Mostrar Item Flutuante",
        "Mostrar visualização prévia da definição"
    ],
    "vs/editor/contrib/hover/modesContentHover": [
        "Carregando...",
        "Inspecionar Problema",
        "Verificando se há correções rápidas...",
        "Sem correções rápidas disponíveis",
        "Correção Rápida..."
    ],
    "vs/editor/contrib/inPlaceReplace/inPlaceReplace": [
        "Substituir pelo valor anterior",
        "Substituir pelo próximo valor"
    ],
    "vs/editor/contrib/linesOperations/linesOperations": [
        "Copiar linha acima",
        "&&Copiar a linha acima",
        "Copiar linha abaixo",
        "Co&&piar a linha abaixo",
        "Duplicar seleção",
        "&&Duplicar Seleção",
        "Mover linha para cima",
        "Mo&&ver a linha para cima",
        "Mover linha para baixo",
        "Mover &&linha para baixo",
        "Classificar Linhas Ascendentemente",
        "Classificar Linhas Descendentemente",
        "Cortar Espaço em Branco à Direita",
        "Excluir Linha",
        "Recuar linha",
        "Recuar linha para a esquerda",
        "Inserir linha acima",
        "Inserir linha abaixo",
        "Excluir Tudo à Esquerda",
        "Excluir Tudo à Direita",
        "Unir Linhas",
        "Transpor caracteres ao redor do cursor",
        "Transformar para maiúsculas",
        "Transformar para minúsculas",
        "Transformar em caso de título"
    ],
    "vs/editor/contrib/links/links": [
        "Comando executar",
        "Siga o link",
        "cmd + clique",
        "CTRL + clique",
        "opção + clique",
        "Alt + clique",
        "Falha ao abrir este link porque ele não está bem formatado: {0}",
        "Falha ao abrir este link porque seu destino está faltando.",
        "Abrir link"
    ],
    "vs/editor/contrib/message/messageController": [
        "Não é possível editar no editor somente leitura"
    ],
    "vs/editor/contrib/multicursor/multicursor": [
        "Inserir cursor acima",
        "&&Adicionar Cursor Acima",
        "Inserir cursor abaixo",
        "A&&dicionar Cursor Abaixo",
        "Adicionar Cursores ao Final das Linhas",
        "Adicionar C&&ursores aos Finais de Linha",
        "Inserir cursor abaixo",
        "Adicionar Cursores Acima",
        "Adicionar Seleção ao Próximo Localizar Correspondência",
        "Adicionar &&Próxima Ocorrência",
        "Adicionar Seleção à Correspondência de Localização Anterior",
        "Adicionar O&&corrência Prévia",
        "Mover Última Seleção para Próximo Localizar Correspondência",
        "Mover Última Seleção para Correspondência de Localização Anterior",
        "Selecionar Todas as Ocorrências de Localizar Correspondência",
        "Selecionar todas as &&ocorrências",
        "Alterar todas as ocorrências"
    ],
    "vs/editor/contrib/parameterHints/parameterHints": [
        "Ativar dicas de parâmetro"
    ],
    "vs/editor/contrib/parameterHints/parameterHintsWidget": [
        "{0}, dica"
    ],
    "vs/editor/contrib/peekView/peekView": [
        "Fechar",
        "Cor de fundo da área de visualização do título.",
        "Cor de visualização do título.",
        "Cor da visualização de informações do título.",
        "Cor das bordas e seta da área de visualização",
        "Cor de fundo da área de visualização da lista de resultados.",
        "Cor de primeiro plano para nós de linha na lista de resultados visualizados.",
        "Cor de primeiro plano para nós de arquivos na lista de resultados visualizados.",
        "Cor de fundo da entrada selecionada na visualização da lista de resultados.",
        "Cor da entrada selecionada na visualização da lista de resultados.",
        "Cor de fundo da visualização do editor.",
        "Cor de fundo da separação na visualização rápida do editor.",
        "Corresponder cor de realce com visualização da lista de resultados.",
        "Corresponder cor de realce com visualização do editor.",
        "Corresponder borda de destaque no editor de exibição de peek."
    ],
    "vs/editor/contrib/rename/rename": [
        "Nenhum resultado.",
        "Ocorreu um erro desconhecido durante a resolução do novo nome de local",
        "Renomeando '{0}'",
        "Renomeado '{0}' para '{1}'com sucesso. Resumo: {2}",
        "Falha ao renomear a aplicação de edições",
        "Rename failed to compute edits",
        "Renomear Símbolo",
        "Ativar/desativar a capacidade de visualizar alterações antes de renomear"
    ],
    "vs/editor/contrib/rename/renameInputField": [
        "Renomear entrada. Digite o novo nome e tecle Enter para gravar.",
        "{0} para renomear, {1} para visualizar"
    ],
    "vs/editor/contrib/smartSelect/smartSelect": [
        "Expandir a seleção",
        "&&Expandir Seleção",
        "Seleção de compactação",
        "&&Reduzir Seleção"
    ],
    "vs/editor/contrib/snippet/snippetVariables": [
        "Domingo",
        "Segunda-feira",
        "Terça-feira",
        "Quarta-feira",
        "Quinta-feira",
        "Sexta-feira  ",
        "Sábado",
        "Dom",
        "Seg",
        "Ter",
        "Qua",
        "Qui",
        "Sex",
        "Sáb",
        "Janeiro",
        "Fevereiro",
        "Março",
        "Abril",
        "Mai",
        "Junho",
        "Julho",
        "Agosto",
        "Setembro",
        "Outubro",
        "Novembro",
        "Dezembro",
        "Jan",
        "Fevereiro",
        "Mar",
        "Abr",
        "Mai",
        "Junho",
        "Jul",
        "Agosto",
        "Set",
        "Out",
        "Novembro",
        "Dez"
    ],
    "vs/editor/contrib/suggest/suggestController": [
        "Aceitar '{0}' fez {1} edições adicionais",
        "Ativar sugestões",
    ],
    "vs/editor/contrib/suggest/suggestWidget": [
        "Cor de fundo para a ferramenta de sugestão.",
        "Cor da borda para a ferramenta de sugestão.",
        "Cor de primeiro plano para a ferramenta de sugestão.",
        "Cor de fundo da entrada selecionada da ferramenta de sugestões.",
        "Cor de realce da correspondência na ferramenta de sugestão.",
        "Ler Mais...{0}",
        "Ler menos... {0}",
        "Carregando...",
        "Carregando...",
        "Nenhuma sugestão.",
        "{0} para menos...",
        "{0} para mais...",
        "Item {0}, docs: {1}",
        "{0} para inserir, {1} para substituir",
        "{0} para substituir, {1} para inserir",
        "{0} para aceitar"
    ],
    "vs/editor/contrib/toggleTabFocusMode/toggleTabFocusMode": [
        "Alterne o uso da tecla Tab para mover o foco",
        "Pressionar Tab agora irá mover o foco para o próximo elemento focável",
        "Pressionar Tab inserirá agora o caractere de tabulação"
    ],
    "vs/editor/contrib/tokenization/tokenization": [
        "Desenvolvedor: Forçar Retokenize"
    ],
    "vs/editor/contrib/wordHighlighter/wordHighlighter": [
        "Cor de fundo de um símbolo durante o acesso de leitura, como a leitura de uma variável. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor de plano de fundo de um símbolo durante o acesso de gravação, como gravar em uma variável. A cor não deve ser opaca de modo a não esconder decorações subjacentes.",
        "Cor de fundo de um símbolo durante acesso de leitura, como ao ler uma variável.",
        "Cor de fundo de um símbolo durante acesso de escrita, como ao escrever uma variável.",
        "Cor do marcador da régua de visão geral para destaques de símbolo. A cor não deve ser opaca para não ocultar as decorações subjacentes.",
        "Destaques de cor do marcador régua visão geral para o símbolo de acesso de gravação. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Ir para o próximo símbolo em destaque",
        "Ir para o símbolo de destaque anterior",
        "Destaque de símbolo de gatilho"
    ],
    "vs/platform/configuration/common/configurationRegistry": [
        "Sobreposições da Configuração Padrão",
        "Definir que configurações do editor sejam substituídas para um idioma.",
        "Esta configuração não suporta configurações por linguagem.",
        "Não é possível registrar '{0}'. Isto corresponde a propriedade padrão '\\\\[.*\\\\]$' para descrever configurações do editor específico de linguagem. Use a contribuição 'configurationDefaults'.",
        "Não é possível registrar '{0}'. Esta propriedade já está registrada."
    ],
    "vs/platform/keybinding/common/abstractKeybindingService": [
        "({0}) foi pressionado. Aguardando segunda tecla de pressionamento simultâneo...",
        "A combinação de chave ({0}, {1}) não é um comando."
    ],
    "vs/platform/list/browser/listService": [
        "Área de Trabalho",
        "Mapeia para 'Control' no Windows e Linux e para 'Command' no macOS.",
        "Mapeia para 'Alt' no Windows e Linux e 'Option' no macOS.",
        "O modificador a ser usado para adicionar um item nas listas e árvores para uma multi-seleção com o mouse (por exemplo, no explorer, editores abertos e exibição de scm). Os gestos do mouse 'Aberto para o lado' - se suportado - irão adaptar-se de tal forma que eles não entrem em conflito com o modificador de várias seleções.",
        "Controla como abrir itens em árvores e listas usando o mouse (se suportado). Para os pais com filhos em árvores, essa configuração irá controlar se um único clique expande o pai ou um clique duplo. Note que algumas árvores e listas podem optar por ignorar essa configuração, se não for aplicável. ",
        "Controla se listas e árvores suportam rolagem horizontal na bancada. Atenção: ligar esta configuração tem uma implicação de desempenho.",
        "Controla se as árvores suportam a rolagem horizontal na área de trabalho.",
        "Essa configuração está descontinuada, por favor use '{0}' em vez disso.",
        "Controla o recuo de árvore em pixels.",
        "Controla se a árvore deve renderizar guias de recuo.",
        "Navegação de teclado simples foca elementos que correspondem à entrada de teclado. Correspondência é feita apenas em prefixos.",
        "A navegação por destaques do teclado ilumina elementos que correspondem à entrada do teclado. Navegações subsequentes pra cima e pra baixo percorrerão apenas os elementos em destaque.",
        "Filtrar a navegação de teclado filtrará e ocultará todos os elementos que não corresponderem à entrada do teclado.",
        "Controla o estilo de navegação de teclado para listas e árvores no ambiente de trabalho. Pode ser simples, destaque e filtro.",
        "Controla se a navegação de teclado nas listas e árvores é acionada automaticamente, simplesmente ao digitar. Se definido como 'false', a navegação do teclado é ativada apenas ao executar o comando 'list.toggleKeyboardNavigation', para o qual você pode atribuir um atalho de teclado."
    ],
    "vs/platform/markers/common/markers": [
        "Erro",
        "Aviso",
        "Informação"
    ],
    "vs/platform/theme/common/colorRegistry": [
        "Cor de primeiro plano geral. Essa cor é só usada se não for substituída por um componente.",
        "Cor de primeiro plano geral para mensagens de erro. Essa cor é só usada se não for substituída por um componente.",
        "Cor geral da borda para elementos focalizados. Essa cor é usada somente se não for substituída por um componente.",
        "Uma borda extra em torno de elementos para separá-los dos outros de maior contraste.",
        "Uma borda extra em torno de elementos ativos para separá-los dos outros de maior contraste.",
        "Cor de primeiro plano para links no texto.",
        "Cor de fundo para blocos de código no texto.",
        "Cor de sombra ferramentas como localizar/substituir dentro do editor.",
        "Cor de fundo da caixa de entrada.",
        "Cor de primeiro plano da caixa de entrada.",
        "Borda da caixa de entrada.",
        "Cor da borda das opções ativas em campos de entrada.",
        "A cor da tela de fundo de opções ativadas em campos de entrada.",
        "Cor de fundo de validação de entrada para a severidade de informações.",
        "Cor do primeiro plano de validação de entrada para a severidade de informações.",
        "Cor da borda de validação de entrada para a severidade de informações.",
        "Cor de fundo de validação de entrada para a severidade do aviso.",
        "Cor de primeiro plano de validação de entrada para a severidade do aviso.",
        "Cor da borda de validação para a severidade de avisos.",
        "Cor de fundo de validação de entrada para a severidade do erro.",
        "Cor de primeiro plano de validação de entrada para a severidade do erro.",
        "Cor da borda de validação de entrada para a severidade do erro.",
        "Cor de fundo do menu suspenso.",
        "Cor de primeiro plano do menu suspenso.",
        "Seletor rápido de cor para rótulos de agrupamento.",
        "Seletor rápido de cor para bordas de agrupamentos.",
        "Cor de fundo do distintivo. Distintivos são rótulos de pequenas informações, por exemplo, para a contagem de resultados de pesquisa.",
        "Cor de primeiro plano do distintivo. Distintivos são rótulos de pequenas informações, por exemplo, para a contagem de resultados de pesquisa.",
        "Sombra da barra de rolagem para indicar que a visualização está sendo rolada.",
        "Cor de fundo da barra de rolagem.",
        "Cor de fundo da barra de rolagem quando o cursor do mouse estiver sobre ela.",
        "Cor de fundo da barra de rolagem ao ser clicada.",
        "Cor de fundo da barra de progresso que pode ser mostrada em operações de execução demorada.",
        "Cor do primeiro plano das linhas onduladas de erro no editor.",
        "Cor da borda das caixas de erro no editor.",
        "Cor do primeiro plano de linhas onduladas de aviso no editor.",
        "Cor da borda das caixas de advertência no editor.",
        "Cor de primeiro plano das linhas sinuosas de informações no editor.",
        "Cor da borda das caixas de informações no editor.",
        "Cor de primeiro plano de linhas onduladas de dica no editor.",
        "Cor da borda de caixas de dica no editor.",
        "Cor de plano de fundo do editor.",
        "Cor de primeiro plano padrão do editor.",
        "Cor de plano de fundo das ferramentas de edição, como pesquisar/substituir.",
        "Cor de primeiro plano de widgets do editor, tais como localizar/substituir.",
        "Cor da borda das ferramentas do editor. A cor é usada somente se a ferramenta escolhe ter uma borda e a cor não é substituída por uma ferramenta.",
        "Cor da borda da barra de redimensionamento das ferramentas do editor. A cor será usada apenas se a ferramenta optar por ter uma borda de redimensionamento e se a cor não tiver sido substituída por uma ferramenta.",
        "Cor de seleção do editor.",
        "Cor do texto selecionado para alto contraste.",
        "Cor da seleção em um editor inativo. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor para as regiões com o mesmo conteúdo da seleção. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor da borda para regiões com o mesmo conteúdo da seleção.",
        "Cor da correspondência de pesquisa atual.",
        "Corresponde a cor da outra pesquisa. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor do intervalo que limita a pesquisa. A cor não deve ser opaca para não ocultar as decorações subjacentes.",
        "Cor da borda da correspondência de pesquisa atual.",
        "Cor da borda dos outros resultados de pesquisa.",
        "Cor da borda da extensão limitando a pesquisa. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Destacado abaixo da palavra para o qual é passado o mouse sobre ela. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor de fundo para o item flutuante do editor",
        "A cor do primeiro plano para o foco do editor",
        "Cor da borda para o item flutuante do editor.",
        "Cor de fundo da barra de status sobre o editor.",
        "Cor dos links ativos.",
        "A cor usada para o ícone de ações da lâmpada.",
        "A cor usada para o ícone das ações de correção automática da lâmpada.",
        "Cor de tela de fundo para o texto que foi inserido. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor de fundo para o texto que foi removido. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor de contorno para o texto que foi inserido.",
        "Cor de contorno para o texto que foi removido.",
        "Cor de borda entre dois editores de texto.",
        "Cor de fundo para o item focalizado de Lista/árvore quando a lista/árvore está ativa. Uma árvore/lista de ativa tem o foco do teclado, uma inativa não.",
        "Cor de primeiro plano da para o item focalizado de Lista/árvore quando a lista/árvore está ativa. Uma árvore/lista ativa tem o foco do teclado, uma inativa não.",
        "Cor de fundo para o item selecionado de Lista/árvore quando a lista/árvore está ativa. Uma lista/árvore ativa tem o foco do teclado, uma inativa não.",
        "Cor de primeiro plano para o item selecionado de Lista/árvore quando a lista/árvore está ativa. Uma lista/árvore ativa tem o foco do teclado, uma inativa não.",
        "Cor de fundo para o item selecionado de Lista/árvore quando a lista/árvore está inativa. Uma lista/árvore ativa tem o foco do teclado, uma inativa não.",
        "Cor de primeiro plano para Lista/árvore para o item selecionado quando a lista/árvore está inativa. Uma árvore/lista ativa tem o foco do teclado, um inativo não.",
        "Cor de fundo da Lista/Árvore para o item focalizado quando a lista/árvore está inativa. Uma lista/árvoce tem o foco do teclado e uma inativa não tem.",
        "Cor de fundo de Lista/árvore quando pairando sobre itens usando o mouse.",
        "Primeiro plano da Lista/Árvoce quando passar sobre itens usando o mouse.",
        "Cor de fundo ao arrastar e soltar de Lista/árvore quando movendo itens usando o mouse.",
        "Cor de primeiro plano de Lista/árvore de destaques de correspondências ao pesquisar na  árvore/lista.",
        "Cor de tela de fundo do widget de tipo de filtro em listas e árvores.",
        "Cor de contorno do elemento filtro tipo em listas e árvores.",
        "Cor de contorno do filtro do tipo widget em listas e árvores, quando não houver nenhuma correspondência.",
        "Cor do traço da árvore das guias de recuo.",
        "Cor da borda dos menus.",
        "Cor de primeiro plano dos itens de menu.",
        "Cor de fundo dos itens de menu.",
        "Cor de primeiro plano do item de menu selecionado nos menus.",
        "Cor de fundo do item de menu selecionado nos menus.",
        "Cor da borda do item de menu selecionado nos menus.",
        "Cor de um separador de item de menu nos menus.",
        "Realçar a cor de fundo de um trecho tabstop.",
        "Realçar a cor da borda de um trecho tabstop.",
        "Realçar a cor de fundo do tabstop final de um trecho.",
        "Realçar a cor da borda do stabstop final de um trecho.",
        "Cor do marcador régua visão para localizar correspondências. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor do marcador da régua de visão geral para destaques de seleção. A cor não deve ser opaca para não esconder decorações subjacentes.",
        "Cor do marcador de minimapa para encontrar correspondências.",
        "Cor do marcador de minimapa para a seleção do editor.",
        "Cor do marcador no minimapa para erros.",
        "Cor do marcador de minimapa para avisos.",
        "A cor usada para o ícone de erro de problemas.",
        "A cor usada para o ícone de aviso de problemas.",
        "A cor usada para o ícone de informações de problemas."
    ],
};
